### ISSUE TITLE
Installation problem (error: ‘gdk_display_get_screen’ is deprecated)

### ISSUE THREAD

**Issue by aliulo** [fernandotcl/pa-applet#15]
Hi, any hint of how to fix this problem? Using Debian 9 Stretch 64bit Thanks!

$ make install
Making install in man
make[1]: Entering directory '/home/matja/Downloads/pa-applet-master/man'
make[2]: Entering directory '/home/matja/Downloads/pa-applet-master/man'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/matja/Downloads/pa-applet-master/share/man/man1'
 /usr/bin/install -c -m 644 pa-applet.1 '/home/matja/Downloads/pa-applet-master/share/man/man1'
make[2]: Leaving directory '/home/matja/Downloads/pa-applet-master/man'
make[1]: Leaving directory '/home/matja/Downloads/pa-applet-master/man'
Making install in src
make[1]: Entering directory '/home/matja/Downloads/pa-applet-master/src'
gcc -DHAVE_CONFIG_H -I. -I..  -std=c99 -D_GNU_SOURCE -Wall -Werror -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_REENTRANT -D_REENTRANT -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include    -g -O2 -MT pa_applet-key_grabber.o -MD -MP -MF .deps/pa_applet-key_grabber.Tpo -c -o pa_applet-key_grabber.o `test -f 'key_grabber.c' || echo './'`key_grabber.c
key_grabber.c: In function ‘key_grabber_grab_keys’:
key_grabber.c:87:9: error: ‘gdk_display_get_screen’ is deprecated [-Werror=deprecated-declarations]
         GdkScreen *screen = gdk_display_get_screen(gdkDisplay, i);
         ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkscreen.h:32:0,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkx.h:28,
                 from key_grabber.c:10:
/usr/include/gtk-3.0/gdk/gdkdisplay.h:56:13: note: declared here
 GdkScreen * gdk_display_get_screen         (GdkDisplay  *display,
             ^~~~~~~~~~~~~~~~~~~~~~
key_grabber.c: In function ‘key_grabber_ungrab_keys’:
key_grabber.c:136:9: error: ‘gdk_display_get_screen’ is deprecated [-Werror=deprecated-declarations]
         GdkScreen *screen = gdk_display_get_screen(gdkDisplay, i);
         ^~~~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkscreen.h:32:0,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkx.h:28,
                 from key_grabber.c:10:
/usr/include/gtk-3.0/gdk/gdkdisplay.h:56:13: note: declared here
 GdkScreen * gdk_display_get_screen         (GdkDisplay  *display,
             ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:433: recipe for target 'pa_applet-key_grabber.o' failed
make[1]: *** [pa_applet-key_grabber.o] Error 1
make[1]: Leaving directory '/home/matja/Downloads/pa-applet-master/src'
Makefile:367: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by fernandotcl** [comment]
As you mentioned in the commit message, the deprecation fix is already in master.

**Comment by aliulo** [comment]
Dear fernandotcl, what does "deprecation fix is already in master" mean? What are the steps for me to do the installation?

**Comment by fernandotcl** [comment]
I'm sorry, @aliulo, but this isn't a support channel. I can't guide you through the process of compiling software. Please rely on your distribution's forums or whatever other support channel.
