### ISSUE TITLE
i3wn multiple run

### ISSUE THREAD

**Issue by pirrazium** [fernandotcl/pa-applet#25]
For autostart in i3wm you should add line 
<pre>
exec --no-startup-id pa-applet
</pre>
but if you restart(without log-out) with standard bindsym $mod+shift+r aka restart you will get another applet in status bar.
Can u make some check for another running PID applet ?

**Comment by n-st** [comment]
You can perform that check externally, no need to modify `pa-applet` itself:

    exec --no-startup-id pgrep pa-applet || pa-applet
